env:
  matrix:
    - TZ=Europe/London
    - TZ=America/Los_Angeles

os:
  - linux

language: r
sudo: false
cache: packages

addons:
  apt:
    update: TRUE

r_packages:
  - covr
  - rmarkdown

after_success:
  - Rscript -e 'covr::codecov()'

