---
title: "13. Circadian Rhythm Analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{13. Circadian Rhythm Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Circadian rhythm are the physical, mental, and behavioral changes an organism experiences over a 24-hour cycle. GGIR facilitates a number of techniques to quantify the movement-component of circadian rhythms as discussed in this chapter.

Most of the techniques are applied in both GGIR part 2 and 6. The main differences between these implementations are:

- In GGIR part 2 the circadian rhythm analysis tries to use every valid data point in the recording.
- In GGIR part 6 the circadian rhythm analysis uses a specific time window as defined by the user, e.g. from first wake-up time till before last wake-up time, and omits entire days that are considered invalid or incomplete.

As a result, when your intention is to compare physical activity or sleep estimates derived in GGIR, part 6 estimates ensure that the same days and time points are used as in the other parts of GGIR. Whereas, part 2 does not attempt to do so.

Further, part 6 offers a few additional circadian rhythm estimates such as DFA (discussed below), and when fragmentation analysis is turned on (see parameter `frag.metrics` as discussed in the [next chapter](https://wadpac.github.io/GGIR/articles/chapter14_BehaviouralFragmentation.html)) activity and sleep fragmentation are also estimated.

## MXLX

MXLX looks for the continuous least (LX) and most (MX) active X hour window in a day, where X is defined by parameter `winhr`. For both LX and MX, GGIR calculates the average acceleration, the start time, and if argument `iglevels` is specified also the intensity gradient. If parameter `winhr` is a vector then MX and LX are derived for each value in the vector.

Within GGIR part 2 MXLX is calculated per calendar day and, if argument `qwindow` is specified, per segment of the day. Within GGIR part 6 MXLX is calculated per [window](https://wadpac.github.io/GGIR/articles/chapter12_TimeUseAnalysis.html#defining-the-time-windows). If used in combination with the GENEActiv or Axivity accelerometer brands, LUX estimates per LX and MX are also included in GGIR part 6 csv reports.

The MX metric described here should not be confused by the MX metrics as proposed by [Rowlands et al.](https://doi.org/10.1186/s40798-019-0225-9) which looks at accumulated most active time which may not always be continuous in time. The MX metrics by Rowlands et al. are discussed [here](https://wadpac.github.io/GGIR/articles/chapter7_DescribingDataWithoutKnowingSleep.html#sets-of-quantiles-mx-metrics-by-rowlands-et-al-).

## (Extended) Cosinor analysis

The Cosinor analysis quantifies the circadian 24 hour cycle. Cosinor analysis refers to fitting a cosine function to a log transformed time series, while the extended cosinor analysis refers to fitting a non-linear transformation of the traditional cosinor curve to after Marler et al. Statist. Med. 2006 (doi: 10.1002/sim.2466).

Corinos analyssis are not run by default, to tell GGIR to perform these analyse specify parameter `cosinor = TRUE`. The implementation is as follows:

1.  The acceleration metric as specified with parameter `acc.metric` is used.
2.  Acceleration metric values are averaged per minute and expressed in m*g* if the input is in *g*, and then log transformed as `log(acceleration + 1)`.
3.  Invalid data points such as caused by non-wear are set to missing (`NA`) as we do not want the imputation used elsewhere in GGIR to influence the Cosinor analysis. We do this because imputation technique generally come with some assumptions about circadian rhythm.
4.  In part 2 GGIR uses all valid data in the recording while in part 6 we only use the valid data in the interval as defined with parameter `part6Window`, e.g. first wake-up time till last wake-up time.
5.  GGIR looks for the first valid data point in the time series and then selects the maximum integer number of recording days following this data point.
6.  If Day Saving Time occurs in the time series then duplicated timestamps when clock moves backward are ignored and missing timestamps when clock moves forward are inserted as missing values.
7.  Cosinor models are fitted using functions `ActCosinor` and `ActExtendCosinor` from R package [ActCR](https://CRAN.R-project.org/package=ActCR). Here, `ActExtendCosinor` uses an anti-logistic function for the transformation.
8.  The time offset between the start of the time series as used and the following midnight is used to reverse offset the ActCR results, to ensure that acrophase and acrotime can be interpreted relative to midnight.
9.  Time series corresponding to the fitted models are stored inside the part 2 milestone data as stored in output subfolder `meta/ms2.out` to facilitate visual inspection. For the moment they are not used in any GGIR visualisation, but you may want to look them up and try to plot them yourself. They are stored in object `SUM$cosinor_ts`.

## Intradaily Variability (IV) and Interdaily Stability (IS)

IV and IS were first proposed by [Witting W et al. 1990](https://doi.org/10.1016/0006-3223(90)90523-5) and [van Someren EJ, et al. 1996](https://doi.org/10.1016/0006-3223(95)00370-3).

-   IS measures how constant is the routine of activity over several days and ranges from 0 to 1, values close to 1 indicate more constant routine.

-   IV measures the variability in activity hour by hour throughout the days. It ranges from 0 to +$\infty$, value close to 2 indicates more fragmented rhythm, and \>2 indicates ultradian rhythm (very uncommon).

The GGIR implementation of IV and IS since GGIR release 3.1-6 has been described in [Danilevicz et al. 2024](https://doi.org/10.1186/s12874-024-02255-w). This implementation replaces the experimental implementation of IS and IV that was present in GGIR since release 1.5-1. In the experimental implementation we were not sure how to go from raw acceleration signal to an indicator of being active as this aspect was not documented in the original publications. Similarly, we were not sure how to deal with missing data. However, these issues were both resolved in release 3.1-6:

-   Being active is now defined as a mean acceleration metric value above the light physical activity threshold as specified with parameter `threshold.lig`.
-   Missing values are left missing and not imputed, the algorithm now accounts for this.

The new implementation as documented by [Danilevicz et al. 2024](https://doi.org/10.1186/s12874-024-02255-w) is not compatible with the older experimental implementation. Parameters `IVIS.activity.metric`, `IVIS_windowsize_minutes`, `IVIS_epochsize_seconds`, and `IVIS_acc_threshold` that were used before is no longer needed and have been deprecated.

**Cosinor analysis compatible IV and IS**

IS is sometimes used as a measure of behavioural robustness when conducting Cosinor analysis. However, to work with the combination of the two outcomes it seems important that IS is calculated from the same time series. Therefore, when `cosinor = TRUE,` IV and IS are calculated twice: Once as part of the default IV and IS analysis as discussed above, and once as part of the Cosinor analysis using the same log transformed time series.

The Cosinor-compatible IV and IS estimates are stored as output variables `cosinorIV` and `cosinorIS`.

## phi

Phi indicates how correlated the multi-day acceleration time series is with itself when there is an hour shift, also known as first-order auto-correlation from the first-order autoregressive model AR(1). A higher phi value indicates a higher autocorrelation, while a phi close to zero or even negative indicates more fragmented behavior. For a detailed discussion of phi see [Dickey and Fuller (1979)](https://doi.org/10.1080/01621459.1979.10482531) and [Danilevicz et al. 2024](https://doi.org/10.1186/s12874-024-02255-w). Phi is calculated by default in GGIR part 2 and in part 6 only when parameter `part6CR` is set to TRUE.

## Detrended fluctionation analysis (DFA)

### Self-similarity paramerter (SSP)

The self-similarity paramter (SSP) is also known as scaling exponent or alpha. SSP is a real number between zero and two. Values in the range (0, 1) indicate stationary motion behaviour. Values int he range (1, 2 indicate nonstationary motion behaviour. For details see [Mesquita et al 2020](https://doi.org/10.1093/bioinformatics/btaa955) and [Danilevicz et al. 2024](https://doi.org/10.1186/s12874-024-02255-w).

### Activity Balance Index (ABI)

The Activity Balance Index (ABI) was introduced by [Danilevicz et al. 2024](https://doi.org/10.1186/s12874-024-02255-w) and is a transformation of SSP. ABI measures how the activity over the observed period is balanced, higher values reflect a more balanced pattern of activity. ABI is a real number between zero and one and calculated from the acceleration metric time series directly without the need for cut-points.

### Sleep Regularity Index (SRI)

A discussion of the Sleep Regularity Index can be found in
<https://wadpac.github.io/GGIR/articles/SleepRegularityIndex.html>

## Related output

-   MXLX are derived per 24 hours (part 2) and available per day in part2_daysummary.csv, and summarised per recording in part2_summary.csv.

-   MXLX are derived per window (part6) but only stored as recording summary in part6_summary.csv.

-   All other circadian rhythm variables are only derived at recording level. IV, IS, phi, and cosinor analysis variables and stored in part2_summary.csv and part6_summary.csv, while SSP and ABI are only stored in part6_summary.csv.

-   For a more detailed variable dictionary see annex on [GGIR output](https://wadpac.github.io/GGIR/articles/GGIRoutput.html).
