---
title: "11. Physical Activity Fundamentals: Describing the data with cut-points"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{11. Physical Activity Fundamentals: Describing the data with cut-points}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

::: {style="background:#f0f4ff;border-left:4px solid #0054AD;padding:1rem 1.2rem;margin-bottom:1.5rem;border-radius:4px"}

**⏱ Reading time:** ~15 min &nbsp;|&nbsp; **Chapter:** 11 of 14

**What you will learn**

- Why physical activity research uses cut-point-based intensity classes
- How GGIR defines and detects behavioural bouts
- The difference between part 2 and part 5 cut-point parameters

**Prerequisites**

- Read the previous chapter: [Chapter 10: Sleep Analysis](chapter10_SleepAnalysis.html)


**Key terms:** <abbr title="Acceleration thresholds used to classify epochs into intensity categories (inactivity, LIPA, MVPA)">cut-point</abbr>, <abbr title="Moderate-to-Vigorous Physical Activity, defined by acceleration at or above the moderate threshold">MVPA</abbr>, <abbr title="Light Physical Activity, defined as acceleration between the light and moderate thresholds">LIPA</abbr>, <abbr title="A sustained period of time in a given behavioural class satisfying user-specified duration and intensity criteria">behavioural bout</abbr>, <abbr title="A fixed-length time window (default 5 s) over which raw acceleration is summarised">epoch</abbr>, <abbr title="The time window from sleep onset to the end of the last SIB, representing the main daily sleep episode">SPT</abbr>
– see the [full Glossary](Glossary.html) for all definitions.

:::

## Why behavioural classes?

Descriptive variables such as average acceleration per day or recording as discussed in the previous chapter are powerful indicators of physical activity. Extensive evidence exists on their association with physical activity related energy expenditure as measured by indirect calorimetry. Similarly, the scientific value of MX metrics and intensity gradient as discussed in chapter 7 has been shown in several studies (for example: [Rowlands, 2019a](https://pubmed.ncbi.nlm.nih.gov/31318713/); [Rowlands 2019b](https://pubmed.ncbi.nlm.nih.gov/31808014/)). However, the physical activity research community has historically expressed a strong interest in measures of physical activity that can be expressed as time per behavioural class per day. In this chapter we will discuss how GGIR facilitates this.

## Construct definition

A popular approach to define behavioural classes in physical activity research is to distinguish so called intensity levels. Here, it is common to distinguish sedentary behaviour (SB), light physical activity (<abbr title="Light Physical Activity, defined as acceleration between the light and moderate thresholds">LIPA</abbr>), moderate, and vigorous physical activity. The latter two categories are often combined into moderate or vigorous physical activity (<abbr title="Moderate-to-Vigorous Physical Activity, defined by acceleration at or above the moderate threshold">MVPA</abbr>). Inside GGIR we refer to sedentary behaviour as inactivity to emphasize that our methods quantify mainly a lack of activity rather than being in sitting or reclying posture.

However, intensity levels as behavioural classes lack a feasible operational construct definition which has caused methodological discrepancies for decades. An elaborate reflection on this can be found in [this blog post](https://www.accelting.com/why-does-ggir-facilitate-cut-points/).

This situation has forced us to be pragmatic and use a operational construct definition of intensity levels that is feasible for accelerometer data.

## Classification based on cut-points

It is common to classify intensity levels from accelerometer data by evaluating whether the acceleration is below, above, or between certain acceleration level(s). The acceleration magnitude(s) to use as threshold(s), are also known as <abbr title="Acceleration thresholds used to classify epochs into intensity categories (inactivity, LIPA, MVPA)">cut-points</abbr>.

The use of thresholds (cut-points) is intended to be a crude indicator of time spent in intensity levels and sufficient to rank individuals on their amount of time spent in these behaviours. The cut-point approach has indisputably been the most powerful method so far to drive physical activity research.

See [published cut-points and how to use them](https://wadpac.github.io/GGIR/articles/CutPoints.html) as guidance for choosing cut-points for your dataset.


As discussed in more detail further down, the acceleration (intensity) level classification is done in GGIR parts 2 and 5.

## Epoch length

Although accelerometers collect data at much higher sampling frequency, we only work with aggregated values (e.g. 1 or 5 second <abbr title="A fixed-length time window (default 5 s) over which raw acceleration is summarised">epochs</abbr>) for the following reasons:

1.  Accelerometers are often used to describe patterns in metabolic energy expenditure. Metabolic energy expenditure is typically defined per breath or per minute (indirect calorimetry), per day (room calorimeter), or per multiple days (doubly labelled water method). In order to evaluate our methods against these reference standards, we need to work with a similar time resolution.

2.  Collapsing the data to epoch summary measures helps to standardise our output across data collected with different sampling frequencies between studies.

3.  There is little evidence that the raw data is an accurate representation of body acceleration. All scientific evidence on the validity of accelerometer data has so far been based on epoch aggregates.

Short epoch lengths, such as 1 or 5 seconds, are more sensitive to sporadic behaviours and often combined with bout detection to identify MVPA only as a sustained behaviour.

Longer epochs, such as 30 or 60 seconds, do not have this problem and are therefore easier to use without bout detection.

The epoch length in GGIR is by default 5 seconds, and can be set as the first value of the vector specified by parameter `windowsizes`. Although we discuss epoch length here in the context of MVPA, please note that epoch length influences many of the outcomes by GGIR such as sleep analysis. GGIR part 5 offers the option to aggregate the time series to a 1 minute epoch length in order to do physical activity research at 1 minute resolution while leaving the sleep detection that relies on a shorter epoch length untouched (see parameter `part5_agg2_60seconds=TRUE`).

## Bout detection

<abbr title="A sustained period of time in a given behavioural class satisfying user-specified duration and intensity criteria">Behavioural bouts</abbr> have been used frequently and are defined as sustained time spent ina behavioural class while adhering to specific temporal criteria. GGIR facilitates processing data both with and without accounting for bouts. The motivation to look for bouts can be one of the following:

-   With the idea that only behaviour with a certain minimum duration contributes to certain physiological benefits.

-   To make the classification of behaviour consistent with self-report data, only sensitive to duration of specific duration.

-   To aid studying the fragmentation of behaviour.

-   To account for the sporadic nature of behaviour when working with short epochs.

To define a bout we need to answer a series of questions:

1.  What should the cut-point be?
2.  What should the epoch length be?
3.  What should minimum duration of bout be?
4.  Should we allow for gaps in a bout as in breaks in the behaviour of interest?
5.  If yes to 4, should this be a percentage of the bout duration, an absolute minimum in seconds, or a combination of both?
6.  If yes to 4, are bout gaps counted towards the time spent in bouts?
7.  Do the first and last epoch need to meet the threshold criteria?
8.  In what order are the bouts extracted? For example, if a short MVPA bout is part of a longer Inactivity bout which of the two prevails?
9.  How many bout categories should there be?

GGIR facilitates the following freedom in bout detection:

User decides on:

-   Acceleration thresholds for light, moderate, and vigorous intensity with `mvpathreshold` for part 2, `threshold.lig`, `threshold.mod`, and `threshold.vig` for part 5.

-   Fraction of time for which cut-point criteria need to be met (light, inactive, MVPA) with `boutcriter` for part 2 and `boutcriter.lig`, `boutcriter.mod`, and `boutcriter.vig` for part 5.

-   Bout duration range. In part 2 with `mvpadur` and in part 5 with `boutdur.lig`, `boutdur.mod`, and `boutdur.mvpa`. This functionality is slightly different between part 2 and part 5 as discussed further down.

-   Epoch length with `windowsizes` and `part5_agg2_60second`.

User does NOT decide on:

-   Maximum bout gap of 1 minute, if the fraction of time for which the cut-point criteria need to be met is less than 100%

-   First and last epoch need to meet cut-point criteria.

-   Number of intensity levels, which are always: inactive, light and MVPA.

-   Order in which bouts are calculated (1 MVPA; 2 inactive; 3 Light)

## Controlling the time window of analysis

As discussed in chapter 7, it is possible to tell both GGIR part 2 and part 5 to extract variables per segment of the day. We do this with parameter `qwindow` for which you can find a detailed discussion in Annex [Day segment analysis](https://wadpac.github.io/GGIR/articles/TutorialDaySegmentAnalyses.html).

## Key parameters

The parameters needed for MVPA estimates in GGIR part 2 are different from the parameters used for estimating MVPA, LIPA and Inactivity in part 5.

### Physical activity cut-point parameter GGIR part 2

In GGIR part 2, only MVPA is estimated since sleep has not been classified at that point. The threshold(s) for MVPA as used in GGIR part 2 are set with parameter `mvpathreshold`. You can specify a single value or a vector of multiple values, time spent in MVPA will then be derived with each of them.

GGIR part 2 always provides six distinct approaches to MVPA calculation that are controlled with parameters `mvpathreshold`, `boutcriter`, `mvpadur`, and the first element of vector `windowsizes`. Here, MVPA provides time spent in MVPA based on:

-   5 second, 1 minute or 5 minute epochs and no bouts

-   5 second epochs and 3 different minimum bout duration as specified with parameter `mvpadur`.

### Physical activity cut-point parameter GGIR part 5

The bout durations are each used for separate estimates and not used complimentary to each other as is the case in part 5. For example, specifying `boutdur.mod = c(5, 10)` in part 5 will result in an estimate of time spent in bouts lasting from 5 till 10 minutes and in bouts lasting 10 minutes and longer. For example, a simple scenario could be to consider all bouts of a minimum length of 10 minutes, while it is also possible to subdivide them in bouts lasting [1, 5) [5, 10) and [10, ∞) minutes.

All parameters related to cut-points and bout detection are listed under ["Physical activity parameters"](https://wadpac.github.io/GGIR/articles/GGIRParameters.html#physical-activity-parameters).

## Related output

In GGIR part 2 csv reports you will find:

-   Time spent in MVPA

In GGIR part 5 csv reports you will find:

-   Time spent in MVPA
-   Time spent in LIPA
-   Time spent in inactivity (abbreviated as IN)

In [chapter 7](https://wadpac.github.io/GGIR/articles/chapter7_DescribingDataWithoutKnowingSleep.html) we discussed the structure of the part 2 output. The next chapter ([chapter 12](https://wadpac.github.io/GGIR/articles/chapter12_TimeUseAnalysis.html)) will provide a more detailed discussion of all the part 5 output. For an overview of output variables see the [GGIR output annex](https://wadpac.github.io/GGIR/articles/GGIRoutput.html).

## Minimal example

```r
library(GGIR)
GGIR(
  datadir        = "C:/mydata",
  outputdir      = "C:/myresults",
  mvpathreshold  = c(100, 120),    # MVPA thresholds for ENMO in mg (part 2)
  threshold.lig  = 40,             # LIPA lower threshold for ENMO in mg (part 5)
  threshold.mod  = 100,            # moderate threshold (part 5)
  threshold.vig  = 400             # vigorous threshold (part 5)
)
```

---

::: {style="background:#f8f9fa;border-top:2px solid #dee2e6;padding:1rem 1.2rem;margin-top:2rem;border-radius:4px"}

### Summary

GGIR classifies waking epochs into inactivity, LIPA, and MVPA using user-specified cut-points. Bout detection further filters these classes by requiring a minimum sustained duration. Part 2 estimates MVPA only; part 5 estimates all three classes during waking hours.

### What to read next

➡ [Chapter 12: Time-use Analysis](chapter12_TimeUseAnalysis.html)

### Related materials

- 📄 [Published cut-points for ENMO](https://wadpac.github.io/GGIR/articles/CutPoints.html)
- 📄 [GGIR Output reference](GGIRoutput.html)


:::

<style>
abbr[data-custom-tooltip] {
  cursor: pointer;
  position: relative;
  text-decoration: underline dotted #0054AD;
}
abbr[data-custom-tooltip]:hover::after {
  content: attr(data-custom-tooltip);
  position: absolute;
  bottom: 120%;
  left: 50%;
  transform: translateX(-50%);
  background-color: #2c3e50;
  color: #fff;
  padding: 6px 10px;
  border-radius: 4px;
  white-space: normal;
  width: max-content;
  max-width: 250px;
  font-size: 13px;
  z-index: 1000;
  box-shadow: 0 4px 6px rgba(0,0,0,0.1);
  text-align: center;
  line-height: 1.4;
}
abbr[data-custom-tooltip]:hover::before {
  content: '';
  position: absolute;
  bottom: 100%;
  left: 50%;
  transform: translateX(-50%);
  border: 6px solid transparent;
  border-top-color: #2c3e50;
}
pre {
  position: relative;
}
pre .copy-btn {
  position: absolute;
  top: 4px;
  right: 4px;
  padding: 2px 8px;
  font-size: 12px;
  cursor: pointer;
  background: #f0f0f0;
  border: 1px solid #ccc;
  border-radius: 3px;
  opacity: 0;
  transition: opacity 0.2s;
}
pre:hover .copy-btn {
  opacity: 1;
}
pre .copy-btn.copied {
  background: #2c3e50;
  color: #fff;
  border-color: #2c3e50;
}
</style>
<script>
document.addEventListener("DOMContentLoaded", function() {
  document.querySelectorAll('abbr[title]').forEach(function(abbr) {
    abbr.setAttribute('data-custom-tooltip', abbr.getAttribute('title'));
    abbr.removeAttribute('title');
  });
  document.querySelectorAll('pre').forEach(function(pre) {
    var btn = document.createElement('button');
    btn.className = 'copy-btn';
    btn.textContent = '\ud83d\udccb Copy';
    btn.addEventListener('click', function() {
      var code = pre.querySelector('code');
      var text = code ? code.textContent : pre.textContent;
      navigator.clipboard.writeText(text).then(function() {
        btn.textContent = '\u2705 Copied!';
        btn.classList.add('copied');
        setTimeout(function() {
          btn.textContent = '\ud83d\udccb Copy';
          btn.classList.remove('copied');
        }, 2000);
      });
    });
    pre.appendChild(btn);
  });
});
</script>
