library(GGIR)
context("fragmentation")
test_that("fragmentation calculates the expected fragmentation metric values", {
  
  x = as.integer(c(rep(0,3),rep(1,20),rep(0,4),rep(1,12),rep(0,1),rep(1,15),rep(0,3),rep(1,9),
        rep(0,2),rep(1,2),rep(0,7),rep(1,16),rep(0,9),rep(1,1),rep(0,2),rep(1,8)))
  frag.classes = 1
  set.seed(300)
  ACC = runif(n = length(x), min=0, max=500)
  intensity.thresholds = c(50,100,400)
  out = g.fragmentation(x=x, frag.classes=frag.classes, frag.metrics = c("all"),
                        ACC=ACC,
                        intensity.thresholds=intensity.thresholds)
  expect_that(round(out$mean_0, digits=3),equals(3.875))
  expect_that(round(out$mean_1, digits=3),equals(10.375))
  expect_that(round(out$towardsTP, digits=4),equals(0.2581))
  expect_that(round(out$awayTP, digits=4),equals(0.0964))
  expect_that(round(out$Gini_0, digits=4),equals(0.4009))
  expect_that(round(out$Gini_1, digits=4),equals(0.3907))
  expect_that(round(out$alpha_0, digits=4),equals(1.5458))
  expect_that(round(out$alpha_1, digits=4),equals(1.3725))
  # expect_that(round(out$h_0, digits=4),equals(0.4407))
  # expect_that(round(out$h_1, digits=4),equals(0.3397))
  expect_that(round(out$x0.5_0, digits=4),equals(3.561))
  expect_that(round(out$x0.5_1, digits=4),equals(6.4287))
  expect_that(round(out$W0.5_0, digits=4),equals(0.6452))
  expect_that(round(out$W0.5_1, digits=4),equals(0.9639))
  expect_that(round(out$dfa, digits=4),equals(1.0434))
  expect_that(round(out$InfEn_binary, digits=4),equals(0.8442))
  expect_that(round(out$SampEn_multiclass, digits=4),equals(0.1863))
  expect_that(round(out$InfEn_multiclass, digits=4),equals(0.7335))
  expect_that(round(out$FastApEn_contin, digits=4),equals(0.4313))
  
  # expect_that(round(out$REC_rqa_contin, digits=4),equals(0.0098))
  # expect_that(round(out$DET_rqa_contin, digits=4),equals(0.904))
  # # expect_that(round(out$RATIO_rqa_contin, digits=4),equals(92.3454))
  # # expect_that(round(out$DIV_rqa_contin, digits=4),equals(Inf))
  # expect_that(round(out$Lmax_rqa_contin, digits=4),equals(0))
  # expect_that(round(out$Lmean_rqa_contin, digits=4),equals(113))
  # expect_that(round(out$ENTR_rqa_contin, digits=4),equals(0))
  # expect_that(round(out$LAM_rqa_contin, digits=4),equals(0))
  # expect_that(round(out$Vmax_rqa_contin, digits=4),equals(0))
  # expect_that(round(out$Vmean_rqa_contin, digits=4),equals(0))
})