library(GGIR)
context("gloadlog")
test_that("gloadlog is able to load different log formats", {
  create_test_sleeplog_csv(Nnights=7, advanced=TRUE)
  fn = "testsleeplogfile.csv"
  expect_true(file.exists(fn))
  startdates = data.frame(ID = "123", startdate = "2015-03-23")
  logs = g.loadlog(loglocation=fn,coln1=2,colid=1,nnights=7,sleeplogidnum=TRUE,startdates = startdates, sleeplogsep=",")
  expect_equal(nrow(logs$sleeplog), 7)
  expect_equal(ncol(logs$sleeplog), 5)
  expect_equal(nrow(logs$nonwearlog), 7)
  expect_equal(ncol(logs$nonwearlog), 4)
  expect_equal(nrow(logs$naplog), 7)
  expect_equal(ncol(logs$naplog), 6)
  if (file.exists(fn)) file.remove(fn)
})